server:
  port: 8080

spring:
  application:
    name: api-gateway-service-ecommerce

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE-ECOMMERCE
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE-ECOMMERCE
          predicates:
            - Path=/payments/**
        # you can add delivery, notification, cart, checkout, etc. here
        # - id: delivery-service
        #   uri: lb://DELIVERY-SERVICE-ECOMMERCE
        #   predicates:
        #     - Path=/deliveries/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
