server:
  port: 8083

spring:
  application:
    name: checkout-service-ecommerce

  datasource:
    url: jdbc:mysql://mysql:3306/checkoutdb?createDatabaseIfNotExist=true
    username: root
    password: darshan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:eureka-server/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
