server:
  port: 8094

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/mock_sterling_oms
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

eureka:

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka/

management:

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:

  level:
    root: INFO
    com.kodewala.mocksterling: DEBUG

springdoc:

  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

inventory:
  base-url: http://localhost:8096

payment:
  base-url: http://localhost:8097

notification:
  base-url: http://localhost:8093
