server:
  port: 8088

spring:
  application:
    name: notification-service-ecommerce

  datasource:
    url: jdbc:mysql://mysql:3306/notificationdb?createDatabaseIfNotExist=true
    username: root
    password: darshan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: darshanudupa10@gmail.com
    password: Darsh@10011887$%

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
