server:
  port: 8084

spring:
  application:
    name: order-service-ecommerce
  datasource:
    url: jdbc:mysql://mysql:3306/order_service_1
    username: root
    password: darshan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"

resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
