server:
  port: 8084

spring:
  application:
    name: order-service-ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/order_service_1
    username: root
    password: darshan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    enabled: false        # <-- Disables tracing so it stops looking for a running Zipkin server
    sampling:
      probability: 0.0
  # zipkin:               # <-- Commented out until you run your Zipkin instance
  #   tracing:
  #     endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
