server:
  port: 8086

spring:
  application:
    name: pickup-service-ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/pickupdb?createDatabaseIfNotExist=true
    username: root
    password: darshan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
